### ISSUE TITLE
Support for Ecmascript without semicolons

### ISSUE THREAD

**Issue by ktfleming** [Artawower/turbo-log#3]
Cool package! Do you think it's possible to support the semicolon-less style, as found in [Standard](https://github.com/standard/standard), for example? Currently if I have

```javascript
function test() {
  const foo = 1
  const bar = 2
}
```

and I select the `const foo = 1` line and run `M-x turbo-log-print`, I get

```javascript
function test() {
  const foo = 1
  const bar = 2
}console.log('[line 3][*js*] TCL:  const foo = 1: ', foo);
```

**Comment by Artawower** [comment]
Hello, thanks for the remark! I am aware of this problem, now it is happening because there are various complex cases of carriage position, like this (when your try to select name for example)
```typescript
function testFuncWithBigSignature(
  name: string,
  age: number,
  patronymic?: string,
): string {
  return `${name} is ${age} years old.`
}
```
But now I will use a stack to count the pairwise brackets to better determine the insertion position, and I hope it will help solve this and similar problems.

**Comment by Artawower** [comment]
It should be better now. Also I added support for disabling semicolon for console log, your can configure it with 
`(plist-put turbo-log--ecmascript-configs :include-semicolon nil)` 😊

**Comment by ktfleming** [comment]
Looks like it's working fine, thanks for the quick improvement!
